### PR TITLE
adding error handling

### PR DESCRIPTION
**Pull request by ineiti**
Correctly handle errors in the `services/default/service.go` file.

Error handling is very important. Errors should never be ignored! The least you should do is to `log.Error`, but most often the error should be returned.

### CODE REVIEW

**Comment by JoaoAndreSa** [comment]
Funny thing, I did this today in the `homoProto` branch (kind of the clean v2 of UnLynx). I think I have finished everything in that branch so I will accept this pull request and then merge the master to homoProto and then make a PR.

**Comment by JoaoAndreSa** [comment]
I used instead `log.Fatal` instead of `ErrFatal`. Any big difference between these two functions? Should we use one instead of the other?

**Comment by ineiti** [comment]
Both should in fact not be used and are a witness of poor code, with exceptions (see below):

`log.Fatal(msg)` - stops the program with the given message
`log.ErrFatal(err, msg)` - stops the program **if err != nil** with the given message

So in the best of all worlds, you would always return the error and then handle it accordingly. `log.Fatal` is usually only used if you have a non-recoverable error, like the database returning bad values, and you want to stop before things get worse.

But as far as I see, in the `service/default`, it could happen that some bad data is around, so it should only stop the given round, not the whole node...

**Comment by ineiti** [comment]
I added two handlers `putSurvey` and `getSurvey`, so that we can track if one of the surveys doesn't get correctly stored. Now waiting for Travis to fail ;)

**Comment by ineiti** [comment]
OK, so it seems that the survey-id `191d0355-8706-46a0-9b7f-723ade3055ce` is never registered in host `localhost:2040`, but that this host wants to retrieve the survey, which can of course not work...

https://travis-ci.org/lca1/unlynx/builds/512446576#L3133

As this doesn't happen on localhost, I suppose that you have some protocols or messages that run in parallel.

I see you're using `RegisterProcessor` which then calls the APIs. This is very strange, and you'll have to explain it to me why you did this.
Normally a protocol is much better, as it's easier to make sure that the different parts of the protocol work correctly, and it's easier to test.

Now you'll have to search where the `CreationQuery` is called, and why the `ResponseQuery` is coming in before the `CreationQuery` in `localhost:2040`...

I hope I didn't overlook something.

**Pull request merged**
